### ISSUE TITLE
動けない期間中にやっておいてほしいこと

### ISSUE THREAD

**Issue by YukiYuigishi** [Undecided-Discord/Oshavery#5]
テスト期間中にでる人が担当してください
- [ ] キックオフの日程の決定
- [ ] 開発予定の作成
- [ ] 仕様書の調整(足りなさそうなもののリストアップ)
- [ ] ドキュメントの整理(議事録を1つのページにまとめる リンクを貼るだけでよい)

**Comment by YukiYuigishi** [comment]
/meetingにまとめてある議事録に
![image](https://user-images.githubusercontent.com/64316110/126272781-00b35f9e-e429-414c-a0bd-ba572fd3e01d.png)
ページリストにある議事録をまとめておいてほしいです

**Comment by YukiYuigishi** [comment]
![image](https://user-images.githubusercontent.com/64316110/126273071-9d5191c8-5832-40e5-a380-e7670075362f.png)
こんな感じに載っているので

**Comment by kato-k** [comment]
更新しますた
https://www.clappdon.work/meetings
